"""
ResourceNameEnum Module

Defines enumeration for resource names used in the Constrained Device Application (CDA).
"""

from enum import Enum
from programmingtheiot.common.ConfigConst import (
    CDA_SENSOR_DATA_MSG_RESOURCE,
    CDA_ACTUATOR_CMD_MSG_RESOURCE,
    CDA_ACTUATOR_RESPONSE_MSG_RESOURCE,
    CDA_MGMT_STATUS_MSG_RESOURCE,
    CDA_MGMT_CMD_MSG_RESOURCE,
    CDA_SYSTEM_PERF_MSG_RESOURCE,
    CDA_UPDATE_NOTIFICATIONS_MSG_RESOURCE
)

class ResourceNameEnum(Enum):
    CDA_SENSOR_DATA = CDA_SENSOR_DATA_MSG_RESOURCE
    CDA_ACTUATOR_CMD = CDA_ACTUATOR_CMD_MSG_RESOURCE
    CDA_ACTUATOR_RESPONSE = CDA_ACTUATOR_RESPONSE_MSG_RESOURCE
    CDA_MGMT_STATUS = CDA_MGMT_STATUS_MSG_RESOURCE
    CDA_MGMT_CMD = CDA_MGMT_CMD_MSG_RESOURCE
    CDA_SYSTEM_PERF = CDA_SYSTEM_PERF_MSG_RESOURCE
    CDA_UPDATE_NOTIFICATIONS = CDA_UPDATE_NOTIFICATIONS_MSG_RESOURCE
